data_folder: "data"
data:
  - "AFC.pkl"
  - "TT.pkl"
  - "STA.pkl"
  - "platform.json"
  - "coordinates.csv"

results_folder: "results"
results_subfolder:
  network: "network"
  path: "path"
  itinerary: "itinerary"
  egress: "egress"
  trajectory: "trajectory"
results:
  node: "node_info.pkl"
  link: "link_info.pkl"
  path: "path.pkl"
  pathvia: "pathvia.pkl"
  feas_iti: "feas_iti.pkl"
  AFC_no_iti: "AFC_no_iti.pkl"
  egress_times: "egress_times.pkl"  # auto index
  etd: "etd.pkl"  # columns: [pl_id, x, kde_pdf, kde_cdf, kde_ks_stat, kde_ks_p_value, gamma_pdf, gamma_cdf, gamma_ks_stat, gamma_ks_p_value, lognorm_pdf, lognorm_cdf, lognorm_ks_stat, lognorm_ks_p_value]
  physical_links: "physical_links.csv"  # columns: [`pl_id`, `platform_id`, `uid`]
  assigned: "assigned.pkl"  # auto index
  left: "left.pkl"
  stashed: "stashed.pkl"

figure_folder: "figures"

use_existing:
  network: false
  path: false
  itinerary: false
  trajectory: false

parameters:
  # parameters for path
  k: 10
  theta1: 0.6
  theta2: 600
  transfer_deviation: 2
  # parameters for itinerary
  feas_iti_cnt_limit: 1000
  # parameters for egress
  distribution_type: "kde"  # "kde", "gamma", or "lognorm"
  # parameters for trajectory
  strategy: "random"  # "random" or "greedy"
  step_size: 100

  #    parameters for train types
  # B型车定员1468，超员1820；A型车定员1828, 超员2488
  # 1,2,3,4号线用车为B型车6辆编组，编组形式为：+TC-MP-M1-M2-MP-TC+。
  # TC为司机室拖车，座位数36，面积31.75平方米；MP、M1、M2座位数42，面积33.5平方米。
  TRAIN_B_SEAT: 240
  TRAIN_B_AREA: 197.5  # 座位数，立席面积

  # 7， 10号线为A型车，因为以2018年4月11日数据来算，不可能超员，因此直接按照定员和超员数据来反推一下座位数和立席面积
  TRAIN_A_SEAT: 240
  TRAIN_A_AREA: 265

  # 普通乘客耐受立席密度，通勤乘客耐受立席密度。
  # 普通乘客由陈伟的论文和列车定员得到，取为6.57；通勤乘客参考的是调研时火车南站-高新区间的车厢客流情况（一个车厢325人），立席密度为8.4478
  STD_DENSITY: 6.57
  STD_DENSITY_COMMUTER: 8.45


