data_folder: "data"
data:
  - "AFC.pkl"
  - "TT.pkl"
  - "STA.pkl"
  - "platform.json"
  - "coordinates.csv"

results_folder: "results"
results_subfolder:
  network: "network"
  path: "path"
  itinerary: "itinerary"
  trajectory: "trajectory"
  egress: "egress"
  transfer: "transfer"
results:
  # network:
  node: "node_info.pkl"
  link: "link_info.pkl"
  # path:
  path: "path.pkl"
  pathvia: "pathvia.pkl"
  # itinerary:
  feas_iti: "feas_iti.pkl"
  AFC_no_iti: "AFC_no_iti.pkl"
  # trajectory:
  assigned: "assigned.pkl"  # auto index
  left: "left.pkl"
  stashed: "stashed.pkl"
  # egress:
  egress_times: "egress_times.pkl"  # auto index
  etd: "etd.pkl"  # columns: [pl_id, x, kde_pdf, kde_cdf, kde_ks_stat, kde_ks_p_value, gamma_pdf, gamma_cdf, gamma_ks_stat, gamma_ks_p_value, lognorm_pdf, lognorm_cdf, lognorm_ks_stat, lognorm_ks_p_value]
  physical_links: "physical_links.csv"  # columns: [`pl_id`, `platform_id`, `uid`]
  # transfer:
  transfer_times: "transfer_times.pkl"  # auto index
  ttd: "ttd.pkl"  # columns: [plat_uid1, plat_uid2, kde_pdf, kde_cdf, kde_ks_stat, kde_ks_p_value]
  transfer_links: "transfer_links.csv"  # columns: [`path_id`, `seg_id`, `node1`, `node2`, `p_uid1`, `p_uid2`, `transfer_type`]


figure_folder: "figures"

use_existing:
  network: true
  path: true
  itinerary: true
  trajectory: true

parameters:
  # parameters for path
  k: 10
  theta1: 0.6
  theta2: 600
  transfer_deviation: 2
  # parameters for itinerary
  feas_iti_cnt_limit: 1000  # more than this number, this rid goes to stashed.pkl
  # parameters for egress
  distribution_type: "kde"  # "kde", "gamma", or "lognorm"
  # parameters for trajectory
  strategy: "random"  # "random" or "greedy"
  step_size: 100


